version: '3.9'

services:
  php:
    build:
      context: docker/php
      target: dev
    environment:
      PHP_IDE_CONFIG: serverName=php-payload-validator
    restart: unless-stopped
    volumes:
      - ./:/app

  composer:
    extends:
      service: php
    build:
      target: composer
